const projects = [
  {
    id: "aether", // Mapping AIST brand system to the first slot
    title: "AIST Tashkent",
    category: "Brand System & SMM",
    categoryClass: "branding",
    shortDescription: "Комплексный брендбук и визуальный стиль для образовательного центра",
    year: "2026",
    role: "Content Manager",
    client: "AIST Tashkent",
    tools: ["Figma", "Illustrator", "Photoshop", "After Effects", "Lightroom", "Higgsfield", "Claude", "etc"],
    accentColor: "#001166",
    modalBg: "#28347D",
    forceDarkTheme: true,
    pdf: "New folder/pdf for aist/brandbook fin.pdf",
    graphicImages: [
      "New folder/1.jpg",
      "New folder/2.jpg",
      "New folder/2.png",
      "New folder/3.jpg",
      "New folder/4.jpg",
      "New folder/HIGHLIGHTS (7).jpg",
      "New folder/VMESTO UZTELECOM.jpg",
      "New folder/banner horizontal uzun small.jpg",
      "New folder/blocknot.png",
      "New folder/grade comparison cmyk.jpg",
      "New folder/grow with us reels.jpg",
      "New folder/logo (2).jpg",
      "New folder/meet us reels.jpg",
      "New folder/symbol FINAL.jpg",
      "New folder/t-shirt.png",
      "New folder/visual kpp fin 2.jpg",
      "New folder/visual podval fin.jpg"
    ],
    colors: ["#28347D", "#870202", "#EFBF04", "#ffffff"],
    fonts: ["Cormorant Garamond", "Montserrat"],
    challenge: "Создать целостную визуальную систему для образовательного центра AIST в Ташкенте, которая бы объединяла строгость академических стандартов и привлекала современную аудиторию студентов.",
    solution: "Разработан детальный брендбук, включающий адаптивные логотипы, правила типографики, фирменные орнаментальные паттерны и единый стиль оформления социальных сетей (SMM). Цветовая палитра базируется на глубоком темно-синем цвете (Atlantic Navy) и теплом кремовом оттенке.",
    image: `<img src="aist_card.jpg" alt="AIST Tashkent" style="width: 100%; height: 100%; object-fit: cover; border-radius: 12px;">`,
    mobileImage: `<img src="aist_mobile_card.jpg" alt="AIST Tashkent" style="width: 100%; height: 100%; object-fit: cover; border-radius: 12px;">`,
    modalImage: `<img src="aist_modal.jpg" alt="AIST Tashkent" style="width: 100%; height: 100%; object-fit: cover; border-radius: 12px;">`,
    videos: ["aist_video1.mp4", "aist_video2.mp4", "aist_video3.mp4", "aist_video4.mp4"]
  },
  {
    id: "veloce", // Mapping Wendy's to second slot
    title: "Wendy's UZ / KZ",
    category: "Campaigns & Motion Design",
    categoryClass: "app",
    shortDescription: "Полное дизайн-сопровождение открытий и рекламных кампаний бренда",
    year: "2025",
    role: "Graphic Designer / Marketing Specialist",
    client: "Wendy's Uzbekistan & Kazakhstan",
    tools: ["After Effects", "Photoshop", "Premiere Pro", "Print Design"],
    accentColor: "#c94e18",
    modalBg: "#CE1126",
    forceDarkTheme: true,
    colors: ["#CE1126", "#ffffff", "#00A3DD"],
    fonts: ["GT Walsheim Pro"],
    videos: [
      "for wendy's/ролик фрости финальный.mp4",
      "for wendy's/врапы_5.mp4",
      "for wendy's/бигги сеты ролик_1.mp4",
      "for wendy's/финал ласт.mp4",
      "for wendy's/Comp фин.mp4",
      "for wendy's/MainComp 2 1080.mp4",
      "for wendy's/Untitled-1545_1.mp4"
    ],
    graphicImages: [
      "for wendy's/лайтбокс ситимол 67х85.png",
      "for wendy's/киоск 2160x760.png",
      "for wendy's/бигги и снеки сеул.png",
      "for wendy's/говяж и куриный сеул.png",
      "for wendy's/мясо мясо.jpg",
      "for wendy's/акция кофе.jpg",
      "for wendy's/имидж xalq uchun 7.png",
      "for wendy's/обложка рилс.png",
      "for wendy's/пригласительные рус2.png",
      "for wendy's/пригласительная.png",
      "for wendy's/пригласительные2.jpg",
      "for wendy's/teachers day.jpg",
      "for wendy's/uzmdk rus post.png",
      "for wendy's/4194580.png",
      "for wendy's/IMG_4180.JPG",
      "for wendy's/спайси чикен бургер.jpg",
      "for wendy's/спайси чикен врап.jpg"
    ],
    challenge: "Обеспечить качественное рекламное и визуальное оформление для открытия двух флагманских ресторанов (Юнусобод, Татнефть) и запуска лимитированных линеек меню (Lavash, Breakfasts) в Узбекистане и Казахстане.",
    solution: "Созданы динамичные рекламные motion-ролики для уличных LED-экранов и меню-бордов внутри ресторанов. Разработана наружная печатная реклама (билборды, ситиформаты) и адаптивные темплейты для SMM-публикаций в Instagram.",
    image: `<img src="wendys_card.jpg" alt="Wendy's UZ / KZ" style="width: 100%; height: 100%; object-fit: cover; border-radius: 12px;">`,
    mobileImage: `<img src="wendys_mobile_card.jpg" alt="Wendy's UZ / KZ" style="width: 100%; height: 100%; object-fit: cover; border-radius: 12px;">`,
    modalImage: `<img src="wendys_modal.jpg" alt="Wendy's UZ / KZ" style="width: 100%; height: 100%; object-fit: cover; border-radius: 12px;">`
  },
  {
    id: "chronos", // Mapping Webster Events to third slot
    title: "WUT & WIUT Events",
    category: "Event & Poster Design",
    categoryClass: "web",
    shortDescription: "Разработка торжественной айдентики и печатных материалов для ВУЗов",
    year: "2023-2026 WIUT, 2026-Now WUT",
    role: "Lead Visual Designer",
    client: "Webster University in Tashkent, Westminster International University in Tashkent",
    tools: ["Figma", "Illustrator", "Photoshop", "After Effects", "Lightroom", "Higgsfield", "Claude", "etc"],
    accentColor: "#001166",
    modalBg: "#07428c",
    forceDarkTheme: true,
    colors: ["#001166", "#d97706", "#ffffff"],
    fonts: ["ВСЕ ВОЗМОЖНЫЕ В ПЛАНЕ КРЕАТИВА"],
    graphicImages: [
      "for wiut and wut/finalchella poster3.jpg",
      "for wiut and wut/wiut/portfolio-8.jpg",
      "for wiut and wut/wiut/portfolio-7.jpg",
      "for wiut and wut/amir temur.jpg",
      "for wiut and wut/wiut/portfolio_removed-2.jpg",
      "for wiut and wut/wiut/portfolio_removed-1.jpg",
      "for wiut and wut/navruz banner.png",
      "for wiut and wut/finalchella 3.png",
      "for wiut and wut/wiut/portfolio-15.jpg",
      "for wiut and wut/webster 7 years final 2.jpg",
      "for wiut and wut/wiut/portfolio-19.jpg",
      "for wiut and wut/wiut/portfolio_removed-4.jpg",
      "for wiut and wut/a3 pechat.jpg",
      "for wiut and wut/wiut/portfolio-13.jpg",
      "for wiut and wut/wiut/portfolio-17.jpg",
      "for wiut and wut/hayit.png",
      "for wiut and wut/navruz post 1x1.jpg",
      "for wiut and wut/IMG_7689.png",
      "for wiut and wut/53ddc.jpg",
      "for wiut and wut/5аыы.jpg",
      "for wiut and wut/dssss.jpg"
    ],
    videos: [
      "for wiut and wut/Композиция 1_5.mp4"
    ],
    challenge: "Создать серию праздничных плакатов, уличных баннеров и цифровых материалов для оформления университетских праздников: День Победы (9 Мая), Навруз и 690-летие Амира Темура.",
    solution: "Разработана серия величественных академических концепций дизайна, сочетающих строгую шрифтовую иерарфию (Playfair Display), золотые орнаментальные акценты и национальную символику. Все исходники оптимизированы для широкоформатной печати.",
    image: `<img src="wiut_wut_card.jpg" alt="WUT & WIUT Events" style="width: 100%; height: 100%; object-fit: cover; border-radius: 12px;">`,
    mobileImage: `<img src="wiut_wut_mobile_card.jpg" alt="WUT & WIUT Events" style="width: 100%; height: 100%; object-fit: cover; border-radius: 12px;">`,
    modalImage: `<img src="wiut_wut_modal.jpg" alt="WUT & WIUT Events" style="width: 100%; height: 100%; object-fit: cover; border-radius: 12px;">`
  },
  {
    id: "komorebi", // Mapping Study Sphere to fourth slot
    title: "Study Sphere",
    category: "Consulting & Cover Design",
    categoryClass: "web",
    shortDescription: "Разработка дизайна SMM-шаблонов и брошюр для агентства образования",
    year: "2026",
    role: "Visual Designer",
    client: "Study Sphere Consulting",
    tools: ["Figma", "Illustrator", "Photoshop", "After Effects", "Lightroom", "Higgsfield", "Claude", "etc"],
    accentColor: "#0056f5",
    modalBg: "#000000",
    forceDarkTheme: true,
    colors: ["#0056f5", "#000000", "#ffffff"],
    fonts: ["Neue Montreal"],
    graphicImages: [
      "studysphere/chicago.jpg",
      "studysphere/italiya.png",
      "studysphere/imkoniyat.jpg",
      "studysphere/davlat.png",
      "studysphere/grant.png",
      "studysphere/fondi 2.jpg",
      "studysphere/faqat boylar.jpg",
      "studysphere/3 uzb.jpg",
      "studysphere/5.5.png",
      "studysphere/grantda o'qish.png",
      "studysphere/kimman.png",
      "studysphere/mentor.png",
      "studysphere/mentorlik.jpg",
      "studysphere/orzu.jpg",
      "studysphere/oyiga qancha.jpg",
      "studysphere/red flag.jpg",
      "studysphere/tayyor emasman.jpg",
      "studysphere/visa bermaydi 2.jpg"
    ],
    challenge: "Разработать единый, солидный дизайн-концепт для инстаграм-страницы консалтинговой фирмы. Контент должен выглядеть экспертно, чтобы привлекать абитуриентов, стремящихся в зарубежные ТОП-вузы.",
    solution: "Созданы минималистичные стильные обложки постов и хайлайтс в академических сине-золотых тонах. Для структурирования контента разработан набор кастомных иконок стран и престижных колледжей, дополненных элегантным тиснением.",
    image: `<img src="studysphere_card.jpg" alt="Study Sphere" style="width: 100%; height: 100%; object-fit: cover; border-radius: 12px;">`,
    mobileImage: `<img src="studysphere_mobile_card.jpg" alt="Study Sphere" style="width: 100%; height: 100%; object-fit: cover; border-radius: 12px;">`,
    modalImage: `<img src="studysphere_modal.jpg" alt="Study Sphere" style="width: 100%; height: 100%; object-fit: cover; border-radius: 12px;">`
  },
  {
    id: "sado", // Adding United Drivers as the 5th project
    title: "Freelance",
    category: "Branding & Print Production",
    categoryClass: "branding",
    shortDescription: "Разработка фирменного стиля транспортного сообщества и академии",
    year: "с 2022",
    role: "Graphic, Visual and Motion Designer",
    client: "Vokebowl, United Drivers, Sakura Academy, Kahwa Coffee, Perfetto Food and etc.",
    tools: ["Photoshop", "After Effects", "Illustrator", "InDesign", "3Ds Max", "Autocad", "Higgsfield", "Claude", "etc"],
    accentColor: "#0d3c26",
    modalBg: "#ffffff",
    forceLightTheme: true,
    pdf: "freelance/pdf/brandbook.pdf",
    colors: ["#0d3c26", "#e8e8df", "#8B7340", "#111827"],
    fonts: ["Space Grotesk", "Georgia"],
    graphicImages: [
      "freelance/not just a ride 3.jpg",
      "freelance/fleet 2.jpg",
      "freelance/airport.jpg",
      "freelance/fifa 2 2 2.jpg",
      "freelance/cedu brochure pechat.jpg",
      "freelance/oblojka.jpg",
      "freelance/oblojka2.jpg",
      "freelance/1.jpg",
      "freelance/2.jpg",
      "freelance/3.jpg",
      "freelance/4.jpg",
      "freelance/44.jpg",
      "freelance/6.jpg",
      "freelance/photo.jpg",
      "freelance/shawerma2.jpg.webp",
      "freelance/_.jpg.webp",
      "freelance/_2.jpg.webp",
      "freelance/25235f_3.jpg.webp",
      "freelance/AdobeStock_72798892-.jpg.webp",
      "freelance/Atimoment_AVG_privac.jpg.webp",
      "freelance/IMG_005221_3.jpg.webp"
    ],
    videos: [
      "freelance/воки 1_3.mp4",
      "freelance/Композиция 1.mp4",
      "freelance/Композиция 1_3.mp4"
    ],
    challenge: "Разработать айдентику для ряда образовательных и коммерческих брендов — United Drivers, Vokebowl, Sakura Academy, Kahwa Coffee, Perfetto Food — в разные периоды фриланс-практики. Каждый клиент требовал уникальной визуальной системы под свой характер и носители.",
    solution: "На протяжении 4 лет в роли фриланс-дизайнера занимался визуальным, графическим, принт- и моушн-дизайном. Создавал айдентику, полиграфию, брендированные материалы и анимации — от логотипов и сертификатов до мерча и стендов.",
    image: `<img src="freelance_card.jpg" alt="Freelance" style="width: 100%; height: 100%; object-fit: cover; border-radius: 12px;">`,
    mobileImage: `<img src="freelance_mobile_card.jpg" alt="Freelance" style="width: 100%; height: 100%; object-fit: cover; border-radius: 12px;">`,
    modalImage: `<img src="freelance_modal.jpg" alt="Freelance" style="width: 100%; height: 100%; object-fit: cover; border-radius: 12px;">`
  }
];

if (typeof window !== 'undefined') {
  window.portfolioProjects = projects;
} else if (typeof module !== 'undefined') {
  module.exports = projects;
}
